# fly.toml app configuration file generated for calendar-todo-frontend on 2023-11-22T17:59:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calendar-todo-frontend"
primary_region = "ams"

[[services]]
  http_checks = []
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"